var XIAOQI_CONFIG = {
  show_rating: false,
  show_review: false,
  show_price: false
};

var XIAOQI_DATA = {
  cities: [
    { key: 'guangzhou', name: '广州', emoji: '🌆', count: 22, tags: ['粤菜老字号', '日料拉面街', '老城区咖啡'], active: true },
    { key: 'shantou', name: '汕头', emoji: '🏝️', count: 2, tags: ['烧鸟居酒屋', '海边咖啡'], active: false },
    { key: 'shanghai', name: '上海', emoji: '🏙️', count: 0, tags: ['法租界咖啡', '本帮小馆'], active: false },
    { key: 'beijing', name: '北京', emoji: '🏯', count: 0, tags: ['胡同私厨', '京味儿'], active: false },
    { key: 'chengdu', name: '成都', emoji: '🐼', count: 0, tags: ['火锅天堂', '茶馆小吃'], active: false }
  ],
  categories: [
    { key: 'all', label: '全部' },
    { key: 'cantonese', label: '粤菜中餐 🍲' },
    { key: 'japanese', label: '日料拉面 🍜' },
    { key: 'western', label: '西餐披萨 🍕' },
    { key: 'chaoshan', label: '潮汕汤粉 🍲' },
    { key: 'cafe', label: '咖啡甜品 ☕' },
    { key: 'hotpot', label: '火锅打边 🔥' },
    { key: 'solo', label: '一人食 🍱' }
  ],
  restaurants: [
    {
      id: 1,
      name: '花城苑',
      emoji: '🍲',
      rating: 4.7,
      avg_price: 158,
      district: '天河区',
      cuisine: '粤菜 · 广府菜',
      category: 'cantonese',
      city: 'guangzhou',
      tags: ['家庭聚餐', '经典粤菜', '商务宴请'],
      accent: 'primary',
      stamp: 'restaurant',
      stamp_label: '小齐私藏',
      xiaoqi_said: '老广味道很正的一家粤菜馆，出品稳定，环境也不错，家庭聚餐首选。',
      full_review: '花城苑是小齐常去的粤菜馆之一，在天河区算性价比很高的。环境典雅，适合家庭聚餐或者商务宴请。招牌菜都很有水准，传统广府菜的味道做得很地道。每次来都不会踩雷，是那种「放心带长辈去」的店。',
      signature_dishes: [
        { name: '脆皮烧鹅', emoji: '🦢', price: 88, stars: 3, tag: '招牌', tag_type: 'primary', desc: '皮脆肉嫩，蘸酸梅酱绝了' },
        { name: '清蒸老虎斑', emoji: '🐟', price: 168, stars: 3, tag: '必点', tag_type: 'primary', desc: '火候刚好，鱼肉鲜甜' },
        { name: '虾饺皇', emoji: '🥟', price: 38, stars: 2, tag: '点心', tag_type: 'secondary', desc: '皮薄馅大，虾肉Q弹' }
      ],
      address: '广州市天河区花城大道',
      transport: '地铁5号线五羊邨站步行约8分钟',
      tips: '周末人比较多，建议提前订位。午市点心性价比高。',
      hours: '11:00 - 22:00'
    },
    {
      id: 2,
      name: '博多天妇罗',
      emoji: '🍤',
      rating: 4.6,
      avg_price: 128,
      district: '番禺区/天河区',
      cuisine: '日料 · 天妇罗',
      category: 'japanese',
      city: 'guangzhou',
      tags: ['天妇罗专门店', '约会推荐', '精致日料'],
      accent: 'tertiary',
      stamp: 'restaurant',
      stamp_label: '天妇罗专门',
      xiaoqi_said: '天妇罗做得很专业，面衣薄脆不油腻，食材新鲜，配的酱汁也很讲究。',
      full_review: '博多天妇罗是小齐私心很爱的一家天妇罗专门店。天妇罗的面衣薄得像纸，咬下去咔嚓一声，里面的食材却保留了原汁原味。师傅的火候掌握得非常好，每一样都炸得恰到好处。推荐坐吧台，可以看师傅现场炸，很有仪式感。',
      signature_dishes: [
        { name: '大虾天妇罗', emoji: '🍤', price: 68, stars: 3, tag: '招牌', tag_type: 'primary', desc: '超大只虾，外脆内嫩' },
        { name: '紫苏叶海胆', emoji: '🌿', price: 88, stars: 3, tag: '必点', tag_type: 'primary', desc: '海胆鲜甜，紫苏添香' },
        { name: '蔬菜天妇罗拼盘', emoji: '🥬', price: 48, stars: 2, tag: '推荐', tag_type: 'secondary', desc: '当季蔬菜，清爽解腻' }
      ],
      address: '广州市番禺区（天河有分店）',
      transport: '建议导航前往，附近有停车场',
      tips: '建议坐吧台位，可以看师傅操作。套餐比单点划算。',
      hours: '11:30 - 14:00, 17:30 - 22:00'
    },
    {
      id: 3,
      name: '富士山拉面',
      emoji: '🍜',
      rating: 4.5,
      avg_price: 58,
      district: '天河区',
      cuisine: '日料 · 拉面/沾面',
      category: 'japanese',
      city: 'guangzhou',
      tags: ['一人食首选', '拉面控必去', '深夜食堂'],
      accent: 'primary',
      stamp: 'restaurant',
      stamp_label: '拉面名店',
      xiaoqi_said: '豚骨汤底很浓郁，叉烧入口即化，沾面也很有特色，一个人去吃刚刚好。',
      full_review: '富士山拉面是小齐在天河区最常去的拉面店之一。汤底熬得奶白浓郁，喝一口就知道是真材实料熬出来的。叉烧软嫩到几乎入口即化，溏心蛋也做得很完美。喜欢重口味的推荐沾面，把面蘸进浓汤底里吃，口感更劲道。',
      signature_dishes: [
        { name: '豚骨拉面', emoji: '🍜', price: 48, stars: 3, tag: '招牌', tag_type: 'primary', desc: '经典豚骨汤底，浓郁鲜香' },
        { name: '特制沾面', emoji: '🍝', price: 52, stars: 3, tag: '推荐', tag_type: 'primary', desc: '粗面蘸浓汤，口感超劲道' },
        { name: '叉烧饭', emoji: '🍚', price: 32, stars: 2, tag: '小食', tag_type: 'secondary', desc: '叉烧量足，配米饭绝了' }
      ],
      address: '广州市天河区体育西路',
      transport: '地铁1/3号线体育西路站步行5分钟',
      tips: '饭点要排队，建议错开高峰。可以加面免费。',
      hours: '11:00 - 22:00'
    },
    {
      id: 4,
      name: '真打拉面',
      emoji: '🍜',
      rating: 4.4,
      avg_price: 55,
      district: '天河区',
      cuisine: '日料 · 拉面',
      category: 'japanese',
      city: 'guangzhou',
      tags: ['一人食', '鸡白汤', '性价比高'],
      accent: 'secondary',
      stamp: 'restaurant',
      stamp_label: '鸡白汤名店',
      xiaoqi_said: '鸡白汤拉面很有特色，汤底清爽但鲜味十足，和豚骨是完全不同的风格。',
      full_review: '真打拉面主打的是鸡白汤，和常见的豚骨拉面不太一样。汤底是用鸡骨熬出来的，颜色奶白，喝起来清爽不腻，但鲜味很足。面条是细直面，吸汤能力很好。喜欢清淡一点的拉面的话，这家很推荐。',
      signature_dishes: [
        { name: '鸡白汤拉面', emoji: '🍜', price: 45, stars: 3, tag: '招牌', tag_type: 'primary', desc: '鸡骨熬制，清爽鲜美' },
        { name: '辣味噌拉面', emoji: '🌶️', price: 48, stars: 2, tag: '推荐', tag_type: 'secondary', desc: '微辣开胃，味噌香浓' },
        { name: '煎饺', emoji: '🥟', price: 22, stars: 2, tag: '小食', tag_type: 'secondary', desc: '外脆里嫩，配拉面绝配' }
      ],
      address: '广州市天河区',
      transport: '地铁3号线石牌桥站附近',
      tips: '店面不大，饭点可能要等。推荐加一颗溏心蛋。',
      hours: '11:00 - 21:30'
    },
    {
      id: 5,
      name: '非常厨房',
      emoji: '🥩',
      rating: 4.6,
      avg_price: 188,
      district: '番禺区',
      cuisine: '西餐',
      category: 'western',
      city: 'guangzhou',
      tags: ['约会首选', '氛围感', '牛排'],
      accent: 'error',
      stamp: 'restaurant',
      stamp_label: '约会圣地',
      xiaoqi_said: '番禺区藏得很深的西餐厅，环境很有氛围感，牛排出品稳定，适合纪念日。',
      full_review: '非常厨房是小齐在番禺发现的宝藏西餐厅。位置不太好找，但进去之后会觉得很惊喜。环境布置得很用心，灯光柔和，音乐也很有品味。牛排的熟度掌握得很精准，配菜也很讲究。是那种适合约会或者庆祝特别日子的店。',
      signature_dishes: [
        { name: '澳洲和牛M7', emoji: '🥩', price: 288, stars: 3, tag: '招牌', tag_type: 'primary', desc: '入口即化，肉香浓郁' },
        { name: '黑松露意面', emoji: '🍝', price: 98, stars: 3, tag: '必点', tag_type: 'primary', desc: '松露香气扑鼻，奶油浓郁' },
        { name: '凯撒沙拉', emoji: '🥗', price: 58, stars: 2, tag: '前菜', tag_type: 'secondary', desc: '经典口味，清爽开胃' }
      ],
      address: '广州市番禺区',
      transport: '建议打车或自驾前往',
      tips: '需要提前预约，尤其是周末。建议点套餐更划算。',
      hours: '11:30 - 22:00'
    },
    {
      id: 6,
      name: '华哥猪精品',
      emoji: '🐷',
      rating: 4.7,
      avg_price: 138,
      district: '芳村/荔湾区',
      cuisine: '粤菜 · 猪杂火锅',
      category: 'cantonese',
      city: 'guangzhou',
      tags: ['火锅', '猪杂专门店', '宵夜首选'],
      accent: 'primary',
      stamp: 'restaurant',
      stamp_label: '猪杂天花板',
      xiaoqi_said: '广州猪杂火锅的天花板！猪杂新鲜到会跳舞，粥底绵密，宵夜绝配。',
      full_review: '华哥猪精品是小齐心中广州猪杂火锅的第一名。猪杂都是当天现取的，新鲜程度肉眼可见。粥底火锅的方式很特别，先涮猪杂，最后粥吸收了所有食材的鲜味，喝一碗超满足。晚上来吃宵夜的话，配上一瓶冰镇啤酒，绝了。',
      signature_dishes: [
        { name: '猪杂拼盘', emoji: '🍲', price: 98, stars: 3, tag: '招牌', tag_type: 'primary', desc: '新鲜猪杂，品种丰富' },
        { name: '猪脑', emoji: '🧠', price: 38, stars: 3, tag: '必点', tag_type: 'primary', desc: '嫩滑如豆腐，懂的都懂' },
        { name: '油条', emoji: '🥖', price: 12, stars: 2, tag: '推荐', tag_type: 'secondary', desc: '泡粥里吃，绝配' }
      ],
      address: '广州市荔湾区芳村',
      transport: '地铁1号线芳村站步行约10分钟',
      tips: '晚上人超多，建议早点去或者晚点去。猪肾猪脑是限量的。',
      hours: '17:00 - 凌晨3:00'
    },
    {
      id: 7,
      name: '马家庄',
      emoji: '🍚',
      rating: 4.5,
      avg_price: 78,
      district: '海珠区',
      cuisine: '粤菜 · 黄鳝饭',
      category: 'cantonese',
      city: 'guangzhou',
      tags: ['黄鳝饭', '海珠老店', '家庭聚餐'],
      accent: 'secondary',
      stamp: 'restaurant',
      stamp_label: '黄鳝饭名店',
      xiaoqi_said: '黄鳝饭是真的香！米饭粒粒分明，鳝鱼嫩滑，锅巴也好吃。',
      full_review: '马家庄的黄鳝饭是小齐的心头好。一掀开砂锅盖，香气直接扑鼻而来。米饭用的是丝苗米，粒粒分明，吸收了鳝鱼的鲜味。鳝鱼肉嫩滑，没有土腥味。最绝的是锅底的锅巴，金黄酥脆，每次都要刮干净。',
      signature_dishes: [
        { name: '招牌黄鳝饭', emoji: '🍚', price: 88, stars: 3, tag: '招牌', tag_type: 'primary', desc: '米粒分明，鳝鱼鲜嫩' },
        { name: '豉汁排骨', emoji: '🍖', price: 58, stars: 2, tag: '推荐', tag_type: 'secondary', desc: '豉香浓，排骨嫩' },
        { name: '上汤时蔬', emoji: '🥬', price: 28, stars: 2, tag: '解腻', tag_type: 'tertiary', desc: '清爽解腻' }
      ],
      address: '广州市海珠区',
      transport: '地铁2号线江南西站附近',
      tips: '黄鳝饭需要现做，大概等20分钟。建议打电话先预定。',
      hours: '11:00 - 14:30, 17:00 - 21:30'
    },
    {
      id: 8,
      name: '伙少私房菜',
      emoji: '🦪',
      rating: 4.6,
      avg_price: 168,
      district: '越秀区',
      cuisine: '粤菜 · 私房菜',
      category: 'cantonese',
      city: 'guangzhou',
      tags: ['私房菜', '姜油生蚝', '啫啫煲'],
      accent: 'primary',
      stamp: 'restaurant',
      stamp_label: '私房好味',
      xiaoqi_said: '越秀区藏得很深的私房菜，姜油生蚝和啫啫系列都很绝，需要提前订位。',
      full_review: '伙少私房菜是小齐私藏的一家粤式私房菜。位置在越秀区的一条小巷子里，不太好找，但吃过一次就会念念不忘。姜油生蚝是招牌，生蚝肥美，姜油的香气完全渗透进去。啫啫系列也很赞，镬气十足，端上桌还在滋滋作响。',
      signature_dishes: [
        { name: '姜油生蚝', emoji: '🦪', price: 128, stars: 3, tag: '招牌', tag_type: 'primary', desc: '生蚝肥美，姜香四溢' },
        { name: '啫啫鸡煲', emoji: '🍲', price: 88, stars: 3, tag: '必点', tag_type: 'primary', desc: '镬气十足，鸡肉嫩滑' },
        { name: '啫啫黄鳝', emoji: '🐍', price: 98, stars: 2, tag: '推荐', tag_type: 'secondary', desc: '爽脆入味' }
      ],
      address: '广州市越秀区',
      transport: '地铁1号线公园前站步行约10分钟',
      tips: '一定要提前订位，当天去大概率没位。菜量不大，可以多点几样。',
      hours: '17:30 - 22:00'
    },
    {
      id: 9,
      name: '添牛加粿',
      emoji: '🍲',
      rating: 4.5,
      avg_price: 45,
      district: '海珠区',
      cuisine: '潮汕菜 · 汤粉面/火锅',
      category: 'chaoshan',
      city: 'guangzhou',
      tags: ['潮汕牛肉', '一人食', '性价比高'],
      accent: 'tertiary',
      stamp: 'restaurant',
      stamp_label: '潮汕味道',
      xiaoqi_said: '潮汕牛肉粉很正宗，牛肉鲜嫩，汤底清甜，一个人来吃也很舒服。',
      full_review: '添牛加粿是小齐在海珠区常去的潮汕牛肉粉店。汤底是用牛骨熬的，清甜味鲜。牛肉切得薄薄的，烫几秒就熟，嫩得不行。粿条爽滑，吸满了汤汁。想吃得丰盛一点可以点牛肉火锅套餐，各种部位都能尝到。',
      signature_dishes: [
        { name: '招牌牛肉粿条', emoji: '🍜', price: 35, stars: 3, tag: '招牌', tag_type: 'primary', desc: '牛肉鲜嫩，粿条爽滑' },
        { name: '牛肉火锅套餐', emoji: '🍲', price: 98, stars: 3, tag: '推荐', tag_type: 'primary', desc: '多种部位，一次满足' },
        { name: '牛筋丸', emoji: '🥟', price: 18, stars: 2, tag: '加料', tag_type: 'secondary', desc: 'Q弹爆汁' }
      ],
      address: '广州市海珠区',
      transport: '地铁8号线晓港站附近',
      tips: '午市人很多，建议错峰。可以免费加粿条。',
      hours: '10:00 - 22:00'
    },
    {
      id: 10,
      name: '丘大6仔记',
      emoji: '🥟',
      rating: 4.8,
      avg_price: 88,
      district: '海珠区',
      cuisine: '粤菜 · 早茶/热炒',
      category: 'cantonese',
      city: 'guangzhou',
      tags: ['早茶点心', '葵花鸡', '老广最爱'],
      accent: 'primary',
      stamp: 'restaurant',
      stamp_label: '早茶天花板',
      xiaoqi_said: '广州早茶的天花板级别！葵花鸡必点，皮脆肉嫩，每一样点心都很有水准。',
      full_review: '丘大6仔记是小齐心中广州早茶排名前三的存在。葵花鸡是镇店之宝，皮脆得像玻璃，肉嫩多汁，连鸡胸肉都不柴。点心的种类很多，而且每一样都做得很用心，不是那种敷衍的流水货。环境也不错，带长辈来喝早茶绝对有面子。',
      signature_dishes: [
        { name: '葵花鸡', emoji: '🐔', price: 168, stars: 3, tag: '招牌', tag_type: 'primary', desc: '皮脆肉嫩，鸡味十足' },
        { name: '虾饺皇', emoji: '🥟', price: 32, stars: 3, tag: '必点', tag_type: 'primary', desc: '皮薄馅足，虾肉Q弹' },
        { name: '红米肠', emoji: '🌭', price: 28, stars: 2, tag: '推荐', tag_type: 'secondary', desc: '外软内脆，层次丰富' }
      ],
      address: '广州市海珠区',
      transport: '地铁3号线客村站附近',
      tips: '周末喝早茶要早起，9点后基本要排队。葵花鸡限量，去晚了可能没有。',
      hours: '7:30 - 22:00'
    },
    {
      id: 11,
      name: '和苑',
      emoji: '🕊️',
      rating: 4.7,
      avg_price: 128,
      district: '天河区',
      cuisine: '粤菜 · 早茶/热炒',
      category: 'cantonese',
      city: 'guangzhou',
      tags: ['红烧乳鸽', '早茶', '商务宴请'],
      accent: 'secondary',
      stamp: 'restaurant',
      stamp_label: '乳鸽名店',
      xiaoqi_said: '红烧乳鸽是真的绝！皮脆肉嫩多汁，早茶点心也很有水准。',
      full_review: '和苑的红烧乳鸽是小齐每次去必点的。皮烤得酥脆，咬下去会有咔擦的声音，里面的肉却嫩得能爆出汁来。早茶的点心也都很有水准，不是那种敷衍了事的。环境在天河区算很不错的，商务宴请或者家庭聚餐都合适。',
      signature_dishes: [
        { name: '红烧乳鸽', emoji: '🕊️', price: 68, stars: 3, tag: '招牌', tag_type: 'primary', desc: '皮脆肉嫩，爆汁鲜美' },
        { name: '虾饺', emoji: '🥟', price: 28, stars: 2, tag: '推荐', tag_type: 'secondary', desc: '皮薄馅大' },
        { name: '蒸凤爪', emoji: '🍗', price: 26, stars: 2, tag: '经典', tag_type: 'secondary', desc: '软烂脱骨，豉香浓郁' }
      ],
      address: '广州市天河区',
      transport: '地铁3号线体育西路站步行约10分钟',
      tips: '乳鸽一定要趁热吃。周末早茶建议订位。',
      hours: '7:30 - 22:00'
    },
    {
      id: 12,
      name: '深夜食堂 人生酒肆',
      emoji: '🍢',
      rating: 4.6,
      avg_price: 98,
      district: '汕头市',
      cuisine: '日料 · 烧鸟',
      category: 'japanese',
      city: 'shantou',
      tags: ['烧鸟', '深夜食堂', '小酌首选'],
      accent: 'error',
      stamp: 'restaurant',
      stamp_label: '烧鸟居酒屋',
      xiaoqi_said: '汕头的宝藏烧鸟店！日式居酒屋氛围，烤串水准很高，适合小酌。',
      full_review: '人生酒肆是小齐在汕头发现的宝藏居酒屋。店面不大，但氛围特别好，暖黄的灯光，日式的装修，很有日剧里深夜食堂的感觉。烧鸟的水准很在线，每一串都烤得恰到好处。配一杯冰镇的嗨棒，烦恼都烟消云散了。',
      signature_dishes: [
        { name: '鸡皮串', emoji: '🍢', price: 18, stars: 3, tag: '招牌', tag_type: 'primary', desc: '外脆内糯，油脂香气' },
        { name: '鸡腿肉串', emoji: '🍗', price: 22, stars: 3, tag: '必点', tag_type: 'primary', desc: '嫩滑多汁' },
        { name: '提灯', emoji: '🍳', price: 28, stars: 3, tag: '限定', tag_type: 'error', desc: '一口爆浆，懂的都懂' }
      ],
      address: '汕头市',
      transport: '建议导航前往',
      tips: '提灯限量，建议提前预定。适合晚上小酌。',
      hours: '18:00 - 凌晨1:00'
    },
    {
      id: 13,
      name: 'Maybe 买杯咖啡',
      emoji: '☕',
      rating: 4.5,
      avg_price: 28,
      district: '汕头市',
      cuisine: 'Cafe · 咖啡',
      category: 'cafe',
      city: 'shantou',
      tags: ['精品咖啡', '社区小店', '安静办公'],
      accent: 'tertiary',
      stamp: 'local_cafe',
      stamp_label: '社区咖啡',
      xiaoqi_said: '汕头很有温度的一家社区咖啡店，豆子品质不错，环境安静舒服。',
      full_review: 'Maybe 买杯咖啡是小齐在汕头常去的一家社区咖啡店。店名很有意思，「买杯咖啡」，简单直接。老板是个很懂咖啡的人，豆子都是自己烘焙的，定期会换豆单。环境很安静，适合坐下来看看书或者工作一会儿。',
      signature_dishes: [
        { name: '手冲咖啡', emoji: '☕', price: 35, stars: 3, tag: '推荐', tag_type: 'primary', desc: '单品豆，风味层次丰富' },
        { name: 'Dirty', emoji: '🥛', price: 28, stars: 3, tag: '招牌', tag_type: 'primary', desc: '冰牛奶+热浓缩，层次感强' },
        { name: '拿铁', emoji: '☕', price: 26, stars: 2, tag: '经典', tag_type: 'secondary', desc: '奶泡绵密' }
      ],
      address: '汕头市',
      transport: '建议导航前往',
      tips: '座位不多，周末可能满座。可以问老板当日推荐豆。',
      hours: '9:00 - 21:00'
    },
    {
      id: 14,
      name: 'FLOPSY CAFE ROASTER (晓港店)',
      emoji: '☕',
      rating: 4.6,
      avg_price: 35,
      district: '海珠区',
      cuisine: 'Cafe · 咖啡',
      category: 'cafe',
      city: 'guangzhou',
      tags: ['自烘焙', '手冲专门', '社区咖啡'],
      accent: 'tertiary',
      stamp: 'local_cafe',
      stamp_label: '自烘焙名店',
      xiaoqi_said: '广州很有名的自烘焙咖啡店，豆子品质很高，手冲绝了，咖啡爱好者必去。',
      full_review: 'FLOPSY是小齐心中广州自烘焙咖啡店的第一梯队。老板自己烘豆子，豆单很丰富，从浅烘到深烘都有，经常会有新的产地豆。手冲的水准很稳定，能喝出豆子本身的风味。店里还有卖豆子，喜欢的可以买回家自己冲。',
      signature_dishes: [
        { name: '手冲单品', emoji: '☕', price: 38, stars: 3, tag: '招牌', tag_type: 'primary', desc: '多种产地豆可选' },
        { name: '澳白', emoji: '🥛', price: 32, stars: 2, tag: '推荐', tag_type: 'secondary', desc: '奶咖平衡得很好' },
        { name: '可颂', emoji: '🥐', price: 18, stars: 2, tag: '搭配', tag_type: 'secondary', desc: '外酥内软' }
      ],
      address: '广州市海珠区晓港',
      transport: '地铁8号线晓港站步行约5分钟',
      tips: '可以问咖啡师当日推荐。周末人会比较多。',
      hours: '8:30 - 20:00'
    },
    {
      id: 15,
      name: 'Sushi Hanzo半藏 (K11购物中心店)',
      emoji: '🍣',
      rating: 4.7,
      avg_price: 288,
      district: '天河区',
      cuisine: '日料 · 寿司',
      category: 'japanese',
      city: 'guangzhou',
      tags: ['Omakase', '寿司', '约会推荐'],
      accent: 'primary',
      stamp: 'restaurant',
      stamp_label: '寿司名店',
      xiaoqi_said: '广州性价比很高的寿司Omakase，师傅手艺很好，食材新鲜，值得一试。',
      full_review: '半藏是小齐在广州最常去的寿司店之一。K11这家店环境不错，吧台位可以看师傅现场握寿司。Omakase的套餐性价比很高，十几贯寿司吃下来很满足。师傅会根据当天的食材调整菜单，每一贯都有惊喜。',
      signature_dishes: [
        { name: 'Omakase套餐', emoji: '🍣', price: 288, stars: 3, tag: '推荐', tag_type: 'primary', desc: '十多贯寿司，性价比高' },
        { name: '金枪鱼大腹', emoji: '🐟', price: 68, stars: 3, tag: '限定', tag_type: 'error', desc: '入口即化的脂肪香气' },
        { name: '海胆寿司', emoji: '🦔', price: 58, stars: 3, tag: '必点', tag_type: 'primary', desc: '鲜甜浓郁' }
      ],
      address: '广州市天河区K11购物中心',
      transport: '地铁3/5号线珠江新城站直达',
      tips: '建议提前预约吧台位。午市套餐比晚市划算。',
      hours: '11:30 - 14:30, 17:30 - 22:00'
    },
    {
      id: 16,
      name: 'PIPA Trattoria 枇杷小馆',
      emoji: '🍕',
      rating: 4.5,
      avg_price: 118,
      district: '海珠区',
      cuisine: '西餐 · 披萨',
      category: 'western',
      city: 'guangzhou',
      tags: ['意式披萨', '氛围感', '朋友聚餐'],
      accent: 'secondary',
      stamp: 'restaurant',
      stamp_label: '意式小馆',
      xiaoqi_said: '海珠区很有氛围感的意式小馆，披萨是窑烤的，饼边脆脆的很好吃。',
      full_review: '枇杷小馆是小齐在海珠区很喜欢的一家意式餐厅。店面不大，但布置得很温馨，有种在国外小馆子的感觉。披萨是窑烤的，饼边有漂亮的焦斑，外脆内软。意面也做得很地道。周末晚上来，配上一杯红酒，很有感觉。',
      signature_dishes: [
        { name: '玛格丽特披萨', emoji: '🍕', price: 78, stars: 3, tag: '招牌', tag_type: 'primary', desc: '经典口味，窑烤饼底' },
        { name: '帕尔玛火腿披萨', emoji: '🍕', price: 98, stars: 3, tag: '推荐', tag_type: 'primary', desc: '火腿咸香，芝士浓郁' },
        { name: '松露意面', emoji: '🍝', price: 108, stars: 2, tag: '推荐', tag_type: 'secondary', desc: '松露香气十足' }
      ],
      address: '广州市海珠区',
      transport: '地铁8号线晓港站附近',
      tips: '披萨现烤需要等20分钟左右。周末建议订位。',
      hours: '11:30 - 22:00'
    },
    {
      id: 17,
      name: 'CaffeAmore咖啡蛋糕屋 (富邦中心店)',
      emoji: '🍰',
      rating: 4.4,
      avg_price: 38,
      district: '荔湾区',
      cuisine: 'Cafe · 咖啡/蛋糕',
      category: 'cafe',
      city: 'guangzhou',
      tags: ['蛋糕甜品', '老城区咖啡', '下午茶'],
      accent: 'secondary',
      stamp: 'local_cafe',
      stamp_label: '蛋糕咖啡屋',
      xiaoqi_said: '荔湾区的老牌咖啡蛋糕店，蛋糕做得很用心，适合下午茶歇一歇。',
      full_review: 'CaffeAmore是小齐在荔湾区发现的一家宝藏咖啡蛋糕店。开了有些年头了，是老城区里难得的精品咖啡店。蛋糕的种类很多，而且做得很精致，不会太甜腻。咖啡的水准也在线。逛老城区累了，来这里喝杯咖啡吃块蛋糕，很惬意。',
      signature_dishes: [
        { name: '提拉米苏', emoji: '🍰', price: 32, stars: 3, tag: '招牌', tag_type: 'primary', desc: '咖啡香浓，口感绵密' },
        { name: '芝士蛋糕', emoji: '🧀', price: 28, stars: 2, tag: '推荐', tag_type: 'secondary', desc: '浓郁芝士味' },
        { name: '美式咖啡', emoji: '☕', price: 22, stars: 2, tag: '经典', tag_type: 'tertiary', desc: '配蛋糕刚好' }
      ],
      address: '广州市荔湾区富邦中心',
      transport: '地铁1号线西门口站步行约5分钟',
      tips: '蛋糕每天限量，去晚了可能没有想要的口味。',
      hours: '10:00 - 22:00'
    },
    {
      id: 18,
      name: '123COFFEE LAB',
      emoji: '☕',
      rating: 4.5,
      avg_price: 30,
      district: '海珠区',
      cuisine: 'Cafe · 咖啡',
      category: 'cafe',
      city: 'guangzhou',
      tags: ['精品咖啡', '实验室风格', '创意特调'],
      accent: 'tertiary',
      stamp: 'local_cafe',
      stamp_label: '咖啡实验室',
      xiaoqi_said: '海珠区很有个性的咖啡店，实验室风格的装修，创意特调很有意思。',
      full_review: '123COFFEE LAB是一家很有态度的咖啡店。店名里的LAB不是白叫的，店里的装修就是实验室风格，还有很多咖啡相关的器具和豆子展示。除了传统的咖啡，他们家的创意特调也很值得一试，经常会有季节限定的新品。',
      signature_dishes: [
        { name: '创意特调', emoji: '🍹', price: 38, stars: 3, tag: '招牌', tag_type: 'primary', desc: '季节限定，创意满满' },
        { name: '手冲咖啡', emoji: '☕', price: 32, stars: 3, tag: '推荐', tag_type: 'primary', desc: '多种豆子可选' },
        { name: '冰美式', emoji: '🧊', price: 22, stars: 2, tag: '经典', tag_type: 'secondary', desc: '清爽提神' }
      ],
      address: '广州市海珠区',
      transport: '地铁8号线晓港站附近',
      tips: '可以问问店员最近的特调新品。',
      hours: '9:00 - 20:00'
    },
    {
      id: 19,
      name: '佬佬餐厅 (置业大厦店)',
      emoji: '🍲',
      rating: 4.4,
      avg_price: 88,
      district: '番禺区',
      cuisine: '粤菜 · 热炒',
      category: 'cantonese',
      city: 'guangzhou',
      tags: ['番禺美食', '镬气小炒', '家庭聚餐'],
      accent: 'primary',
      stamp: 'restaurant',
      stamp_label: '番禺老牌',
      xiaoqi_said: '番禺的老牌粤菜馆，小炒很有镬气，性价比很高，本地人常去。',
      full_review: '佬佬餐厅是小齐在番禺常去的一家粤菜馆。开了很多年了，是本地人的饭堂。菜的味道很地道，镬气十足，价格也很实惠。虽然环境一般，但胜在味道好、分量足。想吃地道的粤菜小炒，来这里准没错。',
      signature_dishes: [
        { name: '豉椒炒牛肉', emoji: '🥩', price: 48, stars: 3, tag: '招牌', tag_type: 'primary', desc: '牛肉嫩滑，豉椒香浓' },
        { name: '五柳炸蛋', emoji: '🍳', price: 28, stars: 3, tag: '必点', tag_type: 'primary', desc: '外酥内嫩，酸甜开胃' },
        { name: '凉瓜炒牛肉', emoji: '🥒', price: 38, stars: 2, tag: '推荐', tag_type: 'secondary', desc: '经典粤菜' }
      ],
      address: '广州市番禺区置业大厦',
      transport: '地铁3号线市桥站附近',
      tips: '饭点人很多，建议早点去。菜量很大，别点太多。',
      hours: '11:00 - 14:30, 17:00 - 21:30'
    },
    {
      id: 20,
      name: '老椰·海南文昌鸡 (怡乐店)',
      emoji: '🍗',
      rating: 4.3,
      avg_price: 58,
      district: '海珠区',
      cuisine: '海南菜 · 碟头饭',
      category: 'chaoshan',
      city: 'guangzhou',
      tags: ['文昌鸡', '碟头饭', '一人食'],
      accent: 'secondary',
      stamp: 'restaurant',
      stamp_label: '海南风味',
      xiaoqi_said: '海南文昌鸡做得很不错，鸡肉嫩滑，配的蘸料很正宗，碟头饭性价比高。',
      full_review: '老椰是小齐在怡乐路发现的一家海南菜小店。主打文昌鸡碟头饭，价格很实惠。鸡肉是真的嫩，皮滑肉嫩，配上特制的姜蒜蘸料，很有海南那味儿。米饭是鸡油饭，香得不行。一个人来吃个碟头饭，简单又满足。',
      signature_dishes: [
        { name: '文昌鸡饭', emoji: '🍗', price: 38, stars: 3, tag: '招牌', tag_type: 'primary', desc: '皮滑肉嫩，鸡油饭香' },
        { name: '椰子鸡汤', emoji: '🥥', price: 28, stars: 2, tag: '推荐', tag_type: 'secondary', desc: '清甜鲜美' },
        { name: '海南粉', emoji: '🍜', price: 22, stars: 2, tag: '特色', tag_type: 'tertiary', desc: '海南特色' }
      ],
      address: '广州市海珠区怡乐路',
      transport: '地铁8号线中大站步行约10分钟',
      tips: '店面不大，饭点可能要拼桌。',
      hours: '10:30 - 21:00'
    },
    {
      id: 21,
      name: '十二舍·湯物素煮 (江泰潤政店)',
      emoji: '🍲',
      rating: 4.4,
      avg_price: 88,
      district: '海珠区',
      cuisine: '素食 · 火锅',
      category: 'cafe',
      city: 'guangzhou',
      tags: ['素食火锅', '健康养生', '环境清幽'],
      accent: 'tertiary',
      stamp: 'restaurant',
      stamp_label: '素食美学',
      xiaoqi_said: '很有意境的素食火锅店，汤头很鲜，食材讲究，偶尔吃顿素也很舒服。',
      full_review: '十二舍是小齐很喜欢的一家素食餐厅。环境做得很雅致，有种禅意的感觉。素食火锅的汤底是用各种菌菇和蔬菜熬的，鲜得不行，完全不靠味精。食材都很新鲜，很多是有机的。吃腻了大鱼大肉的时候，来这里吃一顿素，肠胃都觉得轻松了。',
      signature_dishes: [
        { name: '菌菇素火锅', emoji: '🍲', price: 98, stars: 3, tag: '招牌', tag_type: 'primary', desc: '汤底鲜美，食材丰富' },
        { name: '手工素菜', emoji: '🥟', price: 38, stars: 2, tag: '推荐', tag_type: 'secondary', desc: '手工制作，口感独特' },
        { name: '时令蔬菜', emoji: '🥬', price: 28, stars: 2, tag: '新鲜', tag_type: 'tertiary', desc: '当季有机蔬菜' }
      ],
      address: '广州市海珠区江泰路',
      transport: '地铁2号线江泰路站附近',
      tips: '建议提前订位。可以问店员当日推荐的时令食材。',
      hours: '11:00 - 21:00'
    },
    {
      id: 22,
      name: '博多舍楽 (金利来店)',
      emoji: '🍜',
      rating: 4.5,
      avg_price: 62,
      district: '天河区',
      cuisine: '日料 · 拉面/沾面',
      category: 'japanese',
      city: 'guangzhou',
      tags: ['博多拉面', '沾面', '炸鸡'],
      accent: 'primary',
      stamp: 'restaurant',
      stamp_label: '博多拉面',
      xiaoqi_said: '正宗的博多豚骨拉面，汤底浓郁，沾面和炸鸡都很推荐。',
      full_review: '博多舍楽是小齐在天河区很喜欢的一家拉面店。主打博多风格的豚骨拉面，汤底熬得很浓郁，拉面的细面很吸汤。沾面也很有特色，粗面蘸浓汤底吃，口感更劲道。炸鸡是意外之喜，外脆内嫩，配拉面绝了。',
      signature_dishes: [
        { name: '博多豚骨拉面', emoji: '🍜', price: 48, stars: 3, tag: '招牌', tag_type: 'primary', desc: '浓郁豚骨汤底' },
        { name: '特制沾面', emoji: '🍝', price: 52, stars: 3, tag: '推荐', tag_type: 'primary', desc: '粗面蘸浓汤，口感劲道' },
        { name: '炸鸡块', emoji: '🍗', price: 28, stars: 3, tag: '必点', tag_type: 'secondary', desc: '外脆内嫩，多汁' }
      ],
      address: '广州市天河区金利来大厦',
      transport: '地铁3号线体育西路站步行约8分钟',
      tips: '饭点要排队，可以错峰去。推荐加一份替玉（加面）。',
      hours: '11:00 - 22:00'
    }
  ]
};
