var XIAOQI_CONFIG = {
  show_rating: false,
  show_review: false,
  show_price: false
};

var XIAOQI_DATA = {
  cities: [
    { key: 'guangzhou', name: '广州', emoji: '🌆', count: 40, tags: ['粤菜老字号', '日料拉面街', '老城区咖啡'], active: true },
    { key: 'shantou', name: '汕头', emoji: '🏝️', count: 2, tags: ['烧鸟居酒屋', '海边咖啡'], active: false },
    { key: 'macau', name: '澳门', emoji: '🎰', count: 2, tags: ['葡国菜', '云吞面'], active: false },
    { key: 'shunde', name: '顺德', emoji: '🐟', count: 1, tags: ['海鲜大排档', '鱼生之乡'], active: false },
    { key: 'shanghai', name: '上海', emoji: '🏙️', count: 0, tags: ['法租界咖啡', '本帮小馆'], active: false },
    { key: 'beijing', name: '北京', emoji: '🏯', count: 0, tags: ['胡同私厨', '京味儿'], active: false },
    { key: 'chengdu', name: '成都', emoji: '🐼', count: 0, tags: ['火锅天堂', '茶馆小吃'], active: false }
  ],
  categories: [
    { key: 'all', label: '全部 🍽️' },
    { key: 'cantonese', label: '粤菜中餐 🥘' },
    { key: 'hotpot', label: '火锅打边 🔥' },
    { key: 'japanese', label: '日料拉面 🍜' },
    { key: 'western', label: '西餐披萨 🍕' },
    { key: 'cafe', label: '咖啡甜品 ☕' },
    { key: 'regional', label: '各地风味 🌶️' }
  ],
  restaurants: [
    {
      id: 1,
      name: "花城苑",
      emoji: "🥘",
      rating: 4.6,
      avg_price: 0,
      district: "天河区",
      cuisine: "广府菜, 粤菜 · 热炒",
      category: "cantonese",
      tags: ['小齐私藏'],
      accent: "primary",
      stamp: "restaurant",
      stamp_label: "小齐私藏",
      xiaoqi_said: "花城苑是小齐的心头好之一，每次去都有新发现～",
      address: "天河区临江大道海心沙岛东区2号楼",
      transport: "🚌 公交: 花果山公园北门 / 防疫站站",
      tips: "",
      city: "guangzhou",
      signature_dishes: []
    },
    {
      id: 2,
      name: "博多天妇罗",
      emoji: "🍤",
      rating: 4.7,
      avg_price: 0,
      district: "天河区",
      cuisine: "日料 · 天妇罗🍤",
      category: "japanese",
      tags: ['小齐私藏'],
      accent: "secondary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "博多天妇罗是小齐的心头好之一，每次去都有新发现～",
      address: "天河区天河路228号正佳广场B1层",
      transport: "🚇 地铁: 体育中心 / 天河南\n🚌 公交: 体育东路 / 体育中心②站",
      tips: "",
      city: "guangzhou",
      signature_dishes: []
    },
    {
      id: 3,
      name: "富士山拉面",
      emoji: "🍜",
      rating: 4.8,
      avg_price: 0,
      district: "天河区",
      cuisine: "日料 · 拉面🍜",
      category: "japanese",
      tags: ['碳水快乐'],
      accent: "secondary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "富士山拉面是小齐的心头好之一，每次去都有新发现～",
      address: "天河区 · 富士山拉面",
      transport: "",
      tips: "",
      city: "guangzhou",
      signature_dishes: []
    },
    {
      id: 4,
      name: "真打拉面",
      emoji: "🍜",
      rating: 4.9,
      avg_price: 0,
      district: "天河区",
      cuisine: "日料 · 拉面🍜",
      category: "japanese",
      tags: ['碳水快乐'],
      accent: "secondary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "真打拉面是小齐的心头好之一，每次去都有新发现～",
      address: "天河区万菱汇广场负一楼72-2铺",
      transport: "🚇 地铁: 石牌桥 / 体育中心\n🚌 公交: 天河公交场总站 / 石牌桥站N3子站(BRT)站",
      tips: "",
      city: "guangzhou",
      signature_dishes: []
    },
    {
      id: 5,
      name: "非常厨房",
      emoji: "🥩",
      rating: 4.5,
      avg_price: 0,
      district: "天河区",
      cuisine: "西餐",
      category: "western",
      tags: ['小齐私藏'],
      accent: "tertiary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "非常厨房是小齐的心头好之一，每次去都有新发现～",
      address: "番禺区 · 非常厨房",
      transport: "",
      tips: "",
      city: "guangzhou",
      signature_dishes: []
    },
    {
      id: 6,
      name: "华哥猪精品",
      emoji: "🍲",
      rating: 4.6,
      avg_price: 0,
      district: "荔湾区",
      cuisine: "粤菜 · 火锅",
      category: "hotpot",
      tags: ['打边炉'],
      accent: "primary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "华哥猪精品是小齐的心头好之一，每次去都有新发现～",
      address: "荔湾区翠园道东朗沙洛新村七巷7号后门",
      transport: "🚇 地铁: 东沙 / 南漖\n🚌 公交: 沙洛市场 / 沙洛村委站",
      tips: "",
      city: "guangzhou",
      signature_dishes: []
    },
    {
      id: 7,
      name: "马家庄",
      emoji: "🥘",
      rating: 4.7,
      avg_price: 0,
      district: "荔湾区",
      cuisine: "粤菜 · 热炒",
      category: "cantonese",
      tags: ['小齐私藏'],
      accent: "primary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "马家庄是小齐的心头好之一，每次去都有新发现～",
      address: "海珠区 · 马家庄",
      transport: "",
      tips: "",
      city: "guangzhou",
      signature_dishes: [
        { name: "黄鳝饭", tag: "招牌", tag_class: "primary", desc: "", price: 0 }
      ]
    },
    {
      id: 8,
      name: "伙少私房菜",
      emoji: "🥘",
      rating: 4.8,
      avg_price: 0,
      district: "越秀区",
      cuisine: "粤菜 · 热炒",
      category: "cantonese",
      tags: ['小齐私藏'],
      accent: "primary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "伙少私房菜是小齐的心头好之一，每次去都有新发现～",
      address: "越秀区沿江中路345号",
      transport: "🚇 地铁: 团一大广场 / 北京路\n🚌 公交: 东堤 / 文德南站",
      tips: "",
      city: "guangzhou",
      signature_dishes: [
        { name: "啫啫系列", tag: "招牌", tag_class: "primary", desc: "", price: 0 },
        { name: "姜油生蚝", tag: "必点", tag_class: "error", desc: "", price: 0 }
      ]
    },
    {
      id: 9,
      name: "添牛加粿",
      emoji: "🍲",
      rating: 4.9,
      avg_price: 0,
      district: "越秀区",
      cuisine: "潮汕菜 · 汤粉面",
      category: "hotpot",
      tags: ['打边炉'],
      accent: "error",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "添牛加粿是小齐的心头好之一，每次去都有新发现～",
      address: "海珠区 · 添牛加粿",
      transport: "",
      tips: "",
      city: "guangzhou",
      signature_dishes: []
    },
    {
      id: 10,
      name: "丘大6仔记",
      emoji: "🥧",
      rating: 4.5,
      avg_price: 0,
      district: "海珠区",
      cuisine: "粤菜 · 早茶",
      category: "cantonese",
      tags: ['早茶首选'],
      accent: "primary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "丘大6仔记是小齐的心头好之一，每次去都有新发现～",
      address: "海珠区滨江东路523号（宜利苑旁）",
      transport: "🚇 地铁: 二沙岛 / 鹭江\n🚌 公交: 海琴湾总站(下渡路) / 中大北门站",
      tips: "",
      city: "guangzhou",
      signature_dishes: [
        { name: "葵花鸡", tag: "招牌", tag_class: "primary", desc: "", price: 0 }
      ]
    },
    {
      id: 11,
      name: "和苑",
      emoji: "🥧",
      rating: 4.6,
      avg_price: 0,
      district: "海珠区",
      cuisine: "粤菜 · 早茶",
      category: "cantonese",
      tags: ['早茶首选'],
      accent: "primary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "和苑是小齐的心头好之一，每次去都有新发现～",
      address: "中国CN 广东省 广州市 天河区 花城大道 68 68号环球都会广场3/3M层 邮政编码: 510623",
      transport: "🚇 地铁: 广州东 / 林和西\n🚌 公交: 广州火车东站总站 / 广州火车东站总站7车道站",
      tips: "",
      city: "guangzhou",
      signature_dishes: [
        { name: "红烧乳鸽", tag: "招牌", tag_class: "primary", desc: "", price: 0 }
      ]
    },
    {
      id: 12,
      name: "深夜食堂  人生酒肆",
      emoji: "🍢",
      rating: 4.7,
      avg_price: 0,
      district: "",
      cuisine: "日料 · 烧鸟",
      category: "japanese",
      tags: ['汕头必吃'],
      accent: "secondary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "深夜食堂  人生酒肆是小齐的心头好之一，每次去都有新发现～",
      address: "龙湖区丹霞庄5栋102铺面",
      transport: "🚌 公交: 合胜市集 / 丹霞庄站",
      tips: "",
      city: "shantou",
      signature_dishes: []
    },
    {
      id: 13,
      name: "Maybe 买杯咖啡",
      emoji: "☕",
      rating: 4.8,
      avg_price: 0,
      district: "龙湖区",
      cuisine: "Cafe · 咖啡",
      category: "cafe",
      tags: ['咖啡续命', '汕头必吃'],
      accent: "secondary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "Maybe 买杯咖啡是小齐的心头好之一，每次去都有新发现～",
      address: "Maybe 买杯咖啡",
      transport: "🚌 公交: 潮阳汽车客运站 / 汽车总站站",
      tips: "",
      city: "shantou",
      signature_dishes: []
    },
    {
      id: 14,
      name: "FLOPSY CAFE ROASTER(晓港店)",
      emoji: "☕",
      rating: 4.9,
      avg_price: 0,
      district: "海珠区",
      cuisine: "Cafe · 咖啡",
      category: "cafe",
      tags: ['咖啡续命'],
      accent: "secondary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "FLOPSY CAFE ROASTER(晓港店)是小齐的心头好之一，每次去都有新发现～",
      address: "海珠区昌岗街道晓港中马路6号105之二",
      transport: "🚇 地铁: 晓港 / 昌岗",
      tips: "",
      city: "guangzhou",
      signature_dishes: [
        { name: "手冲咖啡", tag: "招牌", tag_class: "primary", desc: "", price: 0 }
      ]
    },
    {
      id: 15,
      name: "Sushi Hanzo半藏(K11购物中心店)",
      emoji: "🍣",
      rating: 4.5,
      avg_price: 0,
      district: "海珠区",
      cuisine: "日料 · 寿司🍣",
      category: "japanese",
      tags: ['小齐私藏'],
      accent: "secondary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "Sushi Hanzo半藏(K11购物中心店)是小齐的心头好之一，每次去都有新发现～",
      address: "天河区天河路天环广场地下一层B157b",
      transport: "🚇 地铁: 天河南 / 体育中心南",
      tips: "",
      city: "guangzhou",
      signature_dishes: []
    },
    {
      id: 16,
      name: "PIPA Trattoria 枇杷小馆",
      emoji: "🍕",
      rating: 4.6,
      avg_price: 0,
      district: "天河区",
      cuisine: "西餐 · 披萨🍕",
      category: "western",
      tags: ['约会推荐'],
      accent: "tertiary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "PIPA Trattoria 枇杷小馆是小齐的心头好之一，每次去都有新发现～",
      address: "海珠区滨江东路795号102-1",
      transport: "🚇 地铁: 鹭江 / 二沙岛\n🚌 公交: 海琴湾总站(下渡路) / 珠江广场①站",
      tips: "",
      city: "guangzhou",
      signature_dishes: [
        { name: "披萨🍕", tag: "招牌", tag_class: "primary", desc: "", price: 0 }
      ]
    },
    {
      id: 17,
      name: "CaffeAmore咖啡蛋糕屋(富邦中心店)",
      emoji: "🍰",
      rating: 4.7,
      avg_price: 0,
      district: "海珠区",
      cuisine: "Cafe · 咖啡",
      category: "cafe",
      tags: ['咖啡续命'],
      accent: "secondary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "CaffeAmore咖啡蛋糕屋(富邦中心店)是小齐的心头好之一，每次去都有新发现～",
      address: "荔湾区中山七路富邦中心写字楼21楼2107号",
      transport: "🚇 地铁: 陈家祠 / 华林寺",
      tips: "",
      city: "guangzhou",
      signature_dishes: [
        { name: "蛋糕🍰", tag: "招牌", tag_class: "primary", desc: "", price: 0 }
      ]
    },
    {
      id: 18,
      name: "123COFFEE LAB",
      emoji: "☕",
      rating: 4.8,
      avg_price: 0,
      district: "荔湾区",
      cuisine: "Cafe · 咖啡",
      category: "cafe",
      tags: ['咖啡续命'],
      accent: "secondary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "123COFFEE LAB是小齐的心头好之一，每次去都有新发现～",
      address: "海珠区 · 123COFFEE LAB",
      transport: "",
      tips: "",
      city: "guangzhou",
      signature_dishes: []
    },
    {
      id: 19,
      name: "佬佬餐厅(置业大厦店)",
      emoji: "🥘",
      rating: 4.9,
      avg_price: 0,
      district: "番禺区",
      cuisine: "粤菜 · 热炒",
      category: "cantonese",
      tags: ['小齐私藏'],
      accent: "primary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "佬佬餐厅(置业大厦店)是小齐的心头好之一，每次去都有新发现～",
      address: "番禺区 · 佬佬餐厅(置业大厦店)",
      transport: "",
      tips: "",
      city: "guangzhou",
      signature_dishes: []
    },
    {
      id: 20,
      name: "老椰·海南文昌鸡(怡乐店)",
      emoji: "🐔",
      rating: 4.5,
      avg_price: 0,
      district: "海珠区",
      cuisine: "海南菜 · 碟头饭",
      category: "cantonese",
      tags: ['小齐私藏'],
      accent: "tertiary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "老椰·海南文昌鸡(怡乐店)是小齐的心头好之一，每次去都有新发现～",
      address: "海珠区 · 老椰·海南文昌鸡(怡乐店)",
      transport: "",
      tips: "",
      city: "guangzhou",
      signature_dishes: []
    },
    {
      id: 21,
      name: "十二舍·湯物素煮(江泰潤政店)",
      emoji: "🍲",
      rating: 4.6,
      avg_price: 0,
      district: "海珠区",
      cuisine: "素食 · 火锅",
      category: "hotpot",
      tags: ['打边炉'],
      accent: "error",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "十二舍·湯物素煮(江泰潤政店)是小齐的心头好之一，每次去都有新发现～",
      address: "海珠区江燕路37号自编A1-2栋4-01",
      transport: "🚌 公交: 江南大道南(地铁江泰路站)① / 江南大道南(地铁江泰路站)站",
      tips: "",
      city: "guangzhou",
      signature_dishes: []
    },
    {
      id: 22,
      name: "博多舍楽(金利来店)",
      emoji: "🍜",
      rating: 4.7,
      avg_price: 0,
      district: "海珠区",
      cuisine: "日料 · 拉面🍜",
      category: "japanese",
      tags: ['碳水快乐'],
      accent: "secondary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "博多舍楽(金利来店)是小齐的心头好之一，每次去都有新发现～",
      address: "天河区 · 博多舍楽(金利来店)",
      transport: "",
      tips: "",
      city: "guangzhou",
      signature_dishes: [
        { name: "沾面", tag: "招牌", tag_class: "primary", desc: "", price: 0 },
        { name: "炸鸡", tag: "必点", tag_class: "error", desc: "", price: 0 }
      ]
    },
    {
      id: 23,
      name: "杏福甜品(江泰路店)",
      emoji: "🍮",
      rating: 4.8,
      avg_price: 0,
      district: "海珠区",
      cuisine: "甜品 · 广式甜品",
      category: "cafe",
      tags: ['小齐私藏'],
      accent: "secondary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "杏福甜品(江泰路店)是小齐的心头好之一，每次去都有新发现～",
      address: "海珠区江燕路59号亚朵酒店首层",
      transport: "🚇 地铁: 江泰路 / 昌岗\n🚌 公交: 江南大道南(地铁江泰路站)① / 江南大道南(地铁江泰路站)站",
      tips: "",
      city: "guangzhou",
      signature_dishes: [
        { name: "杏仁豆腐", tag: "招牌", tag_class: "primary", desc: "", price: 0 },
        { name: "菠萝冰", tag: "必点", tag_class: "error", desc: "", price: 0 },
        { name: "香啡蛋球", tag: "推荐", tag_class: "tertiary", desc: "", price: 0 }
      ]
    },
    {
      id: 24,
      name: "鸣阁·菌菇火锅养生美食(野斋店)",
      emoji: "🍲",
      rating: 4.9,
      avg_price: 0,
      district: "海珠区",
      cuisine: "粤菜 · 火锅",
      category: "hotpot",
      tags: ['打边炉'],
      accent: "primary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "鸣阁·菌菇火锅养生美食(野斋店)是小齐的心头好之一，每次去都有新发现～",
      address: "荔湾区 · 鸣阁·菌菇火锅养生美食(野斋店)",
      transport: "",
      tips: "",
      city: "guangzhou",
      signature_dishes: []
    },
    {
      id: 25,
      name: "雅苑餐厅(朝天路店)",
      emoji: "🥘",
      rating: 4.5,
      avg_price: 0,
      district: "荔湾区",
      cuisine: "粤菜 · 热炒",
      category: "cantonese",
      tags: ['小齐私藏'],
      accent: "primary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "雅苑餐厅(朝天路店)是小齐的心头好之一，每次去都有新发现～",
      address: "越秀区朝天路14号",
      transport: "🚇 地铁: 公园前 / 纪念堂",
      tips: "",
      city: "guangzhou",
      signature_dishes: []
    },
    {
      id: 26,
      name: "宋·川菜(珠江新城店)",
      emoji: "🌶️",
      rating: 4.6,
      avg_price: 0,
      district: "越秀区",
      cuisine: "川菜 · 热炒",
      category: "regional",
      tags: ['小齐私藏'],
      accent: "tertiary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "宋·川菜(珠江新城店)是小齐的心头好之一，每次去都有新发现～",
      address: "天河区花城大道高德置地冬广场4楼417号",
      transport: "🚇 地铁: 花城大道 / 妇儿中心\n🚌 公交: 冼村路中 / 冼村路南站",
      tips: "",
      city: "guangzhou",
      signature_dishes: []
    },
    {
      id: 27,
      name: "川盐府·盐帮川菜(员岗店)",
      emoji: "🌶️",
      rating: 4.7,
      avg_price: 0,
      district: "天河区",
      cuisine: "川菜 · 热炒",
      category: "regional",
      tags: ['小齐私藏'],
      accent: "tertiary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "川盐府·盐帮川菜(员岗店)是小齐的心头好之一，每次去都有新发现～",
      address: "番禺区 · 川盐府·盐帮川菜(员岗店)",
      transport: "",
      tips: "",
      city: "guangzhou",
      signature_dishes: []
    },
    {
      id: 28,
      name: "好呷八大碗(五羊店)",
      emoji: "🌶️",
      rating: 4.8,
      avg_price: 0,
      district: "越秀区",
      cuisine: "湘菜 · 热炒",
      category: "regional",
      tags: ['小齐私藏'],
      accent: "tertiary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "好呷八大碗(五羊店)是小齐的心头好之一，每次去都有新发现～",
      address: "越秀区东风东路750号广联大厦2楼",
      transport: "🚇 地铁: 区庄 / 执信\n🚌 公交: 东风东路(广东工大)② / 东风东路(广东工大)①站",
      tips: "",
      city: "guangzhou",
      signature_dishes: []
    },
    {
      id: 29,
      name: "映日农场无花果鸡(滨江东路店)",
      emoji: "🍲",
      rating: 4.9,
      avg_price: 0,
      district: "越秀区",
      cuisine: "粤菜 · 火锅",
      category: "hotpot",
      tags: ['打边炉'],
      accent: "primary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "映日农场无花果鸡(滨江东路店)是小齐的心头好之一，每次去都有新发现～",
      address: "海珠区明康街11号101房自编之一",
      transport: "🚇 地铁: 二沙岛 / 鹭江",
      tips: "",
      city: "guangzhou",
      signature_dishes: []
    },
    {
      id: 30,
      name: "清润坊甜品(鹭江店)",
      emoji: "🍮",
      rating: 4.5,
      avg_price: 0,
      district: "海珠区",
      cuisine: "甜品 · 广式甜品",
      category: "cafe",
      tags: ['小齐私藏'],
      accent: "secondary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "清润坊甜品(鹭江店)是小齐的心头好之一，每次去都有新发现～",
      address: "海珠区下渡路1号东之26档",
      transport: "🚇 地铁: 鹭江 / 客村\n🚌 公交: 鹭江② / 鹭江①站",
      tips: "",
      city: "guangzhou",
      signature_dishes: []
    },
    {
      id: 31,
      name: "PIPA枇杷小厨披萨研究所",
      emoji: "🍕",
      rating: 4.6,
      avg_price: 0,
      district: "海珠区",
      cuisine: "西餐 · 披萨🍕",
      category: "western",
      tags: ['约会推荐'],
      accent: "tertiary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "PIPA枇杷小厨披萨研究所是小齐的心头好之一，每次去都有新发现～",
      address: "海珠区南泰路绿地越秀海玥小区南门124铺",
      transport: "🚇 地铁: 鹭江 / 二沙岛\n🚌 公交: 海琴湾总站(下渡路) / 珠江广场①站",
      tips: "",
      city: "guangzhou",
      signature_dishes: [
        { name: "披萨🍕", tag: "招牌", tag_class: "primary", desc: "", price: 0 }
      ]
    },
    {
      id: 32,
      name: "乐曼图·泰国餐厅(粤海天地臻味店)",
      emoji: "🍛",
      rating: 4.7,
      avg_price: 0,
      district: "海珠区",
      cuisine: "泰国菜 · 热炒",
      category: "regional",
      tags: ['小齐私藏'],
      accent: "tertiary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "乐曼图·泰国餐厅(粤海天地臻味店)是小齐的心头好之一，每次去都有新发现～",
      address: "天河区 · 乐曼图·泰国餐厅(粤海天地臻味店)",
      transport: "",
      tips: "",
      city: "guangzhou",
      signature_dishes: [
        { name: "咖喱软壳蟹", tag: "招牌", tag_class: "primary", desc: "", price: 0 }
      ]
    },
    {
      id: 33,
      name: "敬茶屋",
      emoji: "🍮",
      rating: 4.8,
      avg_price: 0,
      district: "天河区",
      cuisine: "甜品 · 日式甜品",
      category: "cafe",
      tags: ['小齐私藏'],
      accent: "secondary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "敬茶屋是小齐的心头好之一，每次去都有新发现～",
      address: "天河区 · 敬茶屋",
      transport: "",
      tips: "",
      city: "guangzhou",
      signature_dishes: [
        { name: "抹茶提拉米苏", tag: "招牌", tag_class: "primary", desc: "", price: 0 }
      ]
    },
    {
      id: 34,
      name: "联丰美食(番禺店)",
      emoji: "🥘",
      rating: 4.9,
      avg_price: 0,
      district: "番禺区",
      cuisine: "粤菜 · 粥",
      category: "cantonese",
      tags: ['小齐私藏'],
      accent: "primary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "联丰美食(番禺店)是小齐的心头好之一，每次去都有新发现～",
      address: "番禺区青萝路与新沙渡街交叉口东北角",
      transport: "🚌 公交: 沙湾东村 / 福龙工业区站",
      tips: "",
      city: "guangzhou",
      signature_dishes: []
    },
    {
      id: 35,
      name: "巨记面家(泉威楼店)",
      emoji: "🍜",
      rating: 4.5,
      avg_price: 0,
      district: "番禺区",
      cuisine: "云吞面",
      category: "cantonese",
      tags: ['澳门限定'],
      accent: "primary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "巨记面家(泉威楼店)是小齐的心头好之一，每次去都有新发现～",
      address: "巨记面家(泉威楼店)",
      transport: "",
      tips: "",
      city: "macau",
      signature_dishes: [
        { name: "牛腩", tag: "招牌", tag_class: "primary", desc: "", price: 0 },
        { name: "竹升面", tag: "必点", tag_class: "error", desc: "", price: 0 }
      ]
    },
    {
      id: 36,
      name: "波尔图葡国餐",
      emoji: "🥩",
      rating: 4.6,
      avg_price: 0,
      district: "",
      cuisine: "葡国菜 · 西餐",
      category: "western",
      tags: ['澳门限定'],
      accent: "tertiary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "波尔图葡国餐是小齐的心头好之一，每次去都有新发现～",
      address: "波尔图葡国餐",
      transport: "",
      tips: "",
      city: "macau",
      signature_dishes: [
        { name: "乳猪", tag: "招牌", tag_class: "primary", desc: "", price: 0 },
        { name: "烤羊排", tag: "必点", tag_class: "error", desc: "", price: 0 }
      ]
    },
    {
      id: 37,
      name: "街坊客酒家(基立店)",
      emoji: "🥘",
      rating: 4.7,
      avg_price: 0,
      district: "海珠区",
      cuisine: "粤菜 · 热炒",
      category: "cantonese",
      tags: ['小齐私藏'],
      accent: "primary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "街坊客酒家(基立店)是小齐的心头好之一，每次去都有新发现～",
      address: "海珠区基立南街14号之三",
      transport: "🚇 地铁: 市二宫 / 江南西\n🚌 公交: 基立村 / 基立下道③站",
      tips: "",
      city: "guangzhou",
      signature_dishes: [
        { name: "白贝蒸蛋", tag: "招牌", tag_class: "primary", desc: "", price: 0 },
        { name: "红烧乳鸽", tag: "必点", tag_class: "error", desc: "", price: 0 }
      ]
    },
    {
      id: 38,
      name: "友食肉铺",
      emoji: "🥩",
      rating: 4.8,
      avg_price: 0,
      district: "海珠区",
      cuisine: "西餐",
      category: "western",
      tags: ['小齐私藏'],
      accent: "tertiary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "友食肉铺是小齐的心头好之一，每次去都有新发现～",
      address: "番禺区 · 友食肉铺",
      transport: "",
      tips: "",
      city: "guangzhou",
      signature_dishes: [
        { name: "烤菠萝", tag: "招牌", tag_class: "primary", desc: "", price: 0 },
        { name: "牛排", tag: "必点", tag_class: "error", desc: "", price: 0 }
      ]
    },
    {
      id: 39,
      name: "森焱食馆",
      emoji: "🥘",
      rating: 4.9,
      avg_price: 0,
      district: "海珠区",
      cuisine: "粤菜 · 热炒",
      category: "cantonese",
      tags: ['小齐私藏'],
      accent: "primary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "森焱食馆是小齐的心头好之一，每次去都有新发现～",
      address: "海珠区南华西街道同福中路龙福西二巷2号之一",
      transport: "🚌 公交: 同福中 / 宝岗大道北站",
      tips: "",
      city: "guangzhou",
      signature_dishes: [
        { name: "椒盐九肚鱼", tag: "招牌", tag_class: "primary", desc: "", price: 0 },
        { name: "水蒸鸡", tag: "必点", tag_class: "error", desc: "", price: 0 },
        { name: "香芋扣肉", tag: "推荐", tag_class: "tertiary", desc: "", price: 0 }
      ]
    },
    {
      id: 40,
      name: "亚来亚毅海鲜",
      emoji: "🥘",
      rating: 4.5,
      avg_price: 0,
      district: "海珠区",
      cuisine: "粤菜 · 热炒",
      category: "cantonese",
      tags: ['顺德味道'],
      accent: "primary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "亚来亚毅海鲜是小齐的心头好之一，每次去都有新发现～",
      address: "顺德区左滩村海旁街1号",
      transport: "🚌 公交: 左滩小学 / 左滩村委站",
      tips: "",
      city: "shunde",
      signature_dishes: [
        { name: "啫白鳝", tag: "招牌", tag_class: "primary", desc: "", price: 0 },
        { name: "椒盐竹虫", tag: "必点", tag_class: "error", desc: "", price: 0 },
        { name: "油盐蒸黄脚立", tag: "推荐", tag_class: "tertiary", desc: "", price: 0 }
      ]
    },
    {
      id: 41,
      name: "自造竹升面",
      emoji: "🍜",
      rating: 4.6,
      avg_price: 0,
      district: "顺德区",
      cuisine: "云吞面",
      category: "cantonese",
      tags: ['小齐私藏'],
      accent: "primary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "自造竹升面是小齐的心头好之一，每次去都有新发现～",
      address: "海珠区 · 自造竹升面",
      transport: "",
      tips: "",
      city: "guangzhou",
      signature_dishes: [
        { name: "云吞面", tag: "招牌", tag_class: "primary", desc: "", price: 0 }
      ]
    },
    {
      id: 42,
      name: "Kats coffee咖期",
      emoji: "☕",
      rating: 4.7,
      avg_price: 0,
      district: "越秀区",
      cuisine: "Cafe · 咖啡",
      category: "cafe",
      tags: ['咖啡续命'],
      accent: "secondary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "Kats coffee咖期是小齐的心头好之一，每次去都有新发现～",
      address: "越秀区 · Kats coffee咖期",
      transport: "",
      tips: "",
      city: "guangzhou",
      signature_dishes: [
        { name: "手冲咖啡", tag: "招牌", tag_class: "primary", desc: "", price: 0 }
      ]
    },
    {
      id: 43,
      name: "PROOF Pizza& Eatery披萨和小菜",
      emoji: "🍕",
      rating: 4.8,
      avg_price: 0,
      district: "海珠区",
      cuisine: "西餐 · 披萨🍕",
      category: "western",
      tags: ['约会推荐'],
      accent: "tertiary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "PROOF Pizza& Eatery披萨和小菜是小齐的心头好之一，每次去都有新发现～",
      address: "海珠区 · PROOF Pizza& Eatery披萨和小菜",
      transport: "",
      tips: "",
      city: "guangzhou",
      signature_dishes: [
        { name: "低温牛肉", tag: "招牌", tag_class: "primary", desc: "", price: 0 },
        { name: "披萨🍕", tag: "必点", tag_class: "error", desc: "", price: 0 }
      ]
    },
    {
      id: 44,
      name: "辉记烧烤(隔山新街店)",
      emoji: "🍖",
      rating: 4.9,
      avg_price: 0,
      district: "海珠区",
      cuisine: "烧烤",
      category: "regional",
      tags: ['小齐私藏'],
      accent: "error",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "辉记烧烤(隔山新街店)是小齐的心头好之一，每次去都有新发现～",
      address: "海珠区 · 辉记烧烤(隔山新街店)",
      transport: "",
      tips: "",
      city: "guangzhou",
      signature_dishes: [
        { name: "烤海鲜", tag: "招牌", tag_class: "primary", desc: "", price: 0 },
        { name: "烤熟成鱼", tag: "必点", tag_class: "error", desc: "", price: 0 },
        { name: "烤鸡腿", tag: "推荐", tag_class: "tertiary", desc: "", price: 0 }
      ]
    },
    {
      id: 45,
      name: "云南姑娘·景颇族手抓饭",
      emoji: "🥗",
      rating: 4.5,
      avg_price: 0,
      district: "海珠区",
      cuisine: "云南菜 · 手抓饭",
      category: "regional",
      tags: ['小齐私藏'],
      accent: "tertiary",
      stamp: "",
      stamp_label: "",
      xiaoqi_said: "云南姑娘·景颇族手抓饭是小齐的心头好之一，每次去都有新发现～",
      address: "海珠区 · 云南姑娘·景颇族手抓饭",
      transport: "",
      tips: "",
      city: "guangzhou",
      signature_dishes: [
        { name: "牛肉清汤米线", tag: "招牌", tag_class: "primary", desc: "", price: 0 },
        { name: "稀豆米线", tag: "必点", tag_class: "error", desc: "", price: 0 }
      ]
    }
  ]
};
